# Generated by Django 4.0.4 on 2022-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='education',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=254),
        ),
    ]
