# Generated by Django 4.0.4 on 2022-05-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_contact_address_alter_contact_education_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
